### ISSUE TITLE
Fetching a PokemonSpecies without a Habitat fails

### ISSUE THREAD

**Issue by PikalaxALT** [beastmatser/aiopokeapi#56]
**Describe the bug**
I am attempting to fetch a random PokemonSpecies from the National Pokedex. Due to incomplete data on PokeAPI, some fields are None. However, the package does not properly account for this. In this example, the habitat is None. This is the case for Pokemon starting in gen 4.

```
Traceback (most recent call last):
  File "c:\Users\---\PycharmProjects\PikalaxBOT\venv\Lib\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\---\PycharmProjects\PikalaxBOT\pikalaxbot\ext\hangman.py", line 88, in hangman
    solution = await random.choice(natdex.pokemon_entries).pokemon_species.fetch()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\---\PycharmProjects\PikalaxBOT\venv\Lib\site-packages\aiopoke\utils\minimal_resources.py", line 103, in fetch
    obj: T = await build_map[self.endpoint](self.id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\---\PycharmProjects\PikalaxBOT\venv\Lib\site-packages\aiopoke\utils\cache.py", line 27, in wrapper
    obj: U = await coro(client, name_or_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\---\PycharmProjects\PikalaxBOT\venv\Lib\site-packages\aiopoke\aiopoke_client.py", line 260, in get_pokemon_species
    return PokemonSpecies(**data)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\---\PycharmProjects\PikalaxBOT\venv\Lib\site-packages\aiopoke\objects\resources\pokemon\pokemon_species.py", line 105, in __init__
    self.habitat = MinimalResource(**habitat)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: aiopoke.utils.minimal_resources.MinimalResource() argument after ** must be a mapping, not NoneType
```

**To Reproduce**
- Fetch a PokemonSpecies with ID 387 or higher

**Expected behavior**
The PokemonSpecies is returned

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22] 0.1.4-pypi on Python 3.11.1

**Additional context**

**Comment by PikalaxALT** [comment]
In fixing this bug, Author should research which other fields are nullable, and handle those cases.

**Comment by PikalaxALT** [comment]
Observe that the bugfix is already present in 0.1.5 but this is not yet pushed to pypi.

**Comment by beastmatser** [comment]
Thank you for reporting this issue anyway, pypi should now have [v0.1.5.1](https://github.com/beastmatser/aiopokeapi/releases/tag/v0.1.5.1).
