### ISSUE TITLE
'move_damage_class' field in 'type' should be set to nullable

### ISSUE THREAD

**Issue by Ziqi-Yang** [beastmatser/aiopokeapi#62]
**Describe the bug**
The 'move_damage_class' field in the response of [https://pokeapi.co/api/v2/type/18](https://pokeapi.co/api/v2/type/18) is null. 
Run `get_type(18)` will produce an error like this:
```
Traceback (most recent call last):
  File "/home/zarkli/projects/python/test/./main.py", line 18, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/zarkli/projects/python/test/./main.py", line 12, in main
    type = await client.get_type(18)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zarkli/.local/lib/python3.11/site-packages/aiopoke/utils/cache.py", line 27, in wrapper
    obj: U = await coro(client, name_or_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zarkli/.local/lib/python3.11/site-packages/aiopoke/aiopoke_client.py", line 276, in get_type
    return NaturalGiftType(**data)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zarkli/.local/lib/python3.11/site-packages/aiopoke/objects/resources/pokemon/natural_gift_type.py", line 42, in __init__
    self.move_damage_class = MinimalResource(**move_damage_class)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: aiopoke.utils.minimal_resources.MinimalResource() argument after ** must be a mapping, not NoneType
```
Edit: Don't know whether it is an error of the API itself (i.e. the move_damage_class should never be null. Sorry

**Comment by beastmatser** [comment]
Thank you for bringing this to my attention, it should be fixed in 4256bf85362de79bcf7aa617acfd3fdb322fc9c1. So, make sure you pull the version from Github for your project. Unfortunately, this issue has occured before, with other attributes. It is just not documented wether it could be null, so sometimes there are exceptions, just like the one you found. Thank you for contributing!
