### ISSUE TITLE
TypeError with Past Ability?

### ISSUE THREAD

**Issue by makayla-moster** [beastmatser/aiopokeapi#82]
**Describe the bug**
I get a `TypeError: PastAbility.__init__() got an unexpected keyword argument 'types'` when using `client.get_pokemon(pokemon)` where *I think* any `pokemon` is from gen1 and had a type change (EX: Clefairy, Magneton, Marill). 

Pokemon such as Pikachu, Bulbasaur, Fuecoco, etc. are not having this issue.

**To Reproduce**
1. Construct a function to get pokemon info
2. Use `client = aiopoke.AiopokeClient()`
3. Call `pokeInfo = await client.get_pokemon("clefairy")`
4. Get error

Here's a MWE of my code (in the context of a Discord bot):
```   python 
async def getPoke(self, ctx:commands.Context, *args):
        client = aiopoke.AiopokeClient()
        pokeInfo = await client.get_pokemon("clefairy") #error happens here
        print(pokeInfo)
```

**Expected behavior**
Expected to get information on the input pokemon.

**Error Message**
```
Traceback (most recent call last):
  File "/Users/makaylamoster/Documents/QuelaBot/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/makaylamoster/Documents/QuelaBot/cog_modules/pokemon/cog.py", line 111, in getPoke
    pokeInfo = await client.get_pokemon("clefairy")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/makaylamoster/Documents/QuelaBot/venv/lib/python3.11/site-packages/aiopoke/utils/cache.py", line 27, in wrapper
    obj: U = await coro(client, name_or_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/makaylamoster/Documents/QuelaBot/venv/lib/python3.11/site-packages/aiopoke/aiopoke_client.py", line 253, in get_pokemon
    return Pokemon(**data)
           ^^^^^^^^^^^^^^^
  File "/Users/makaylamoster/Documents/QuelaBot/venv/lib/python3.11/site-packages/aiopoke/objects/resources/pokemon/pokemon.py", line 89, in __init__
    self.past_abilities = [PastAbility(**past_type) for past_type in past_types]
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/makaylamoster/Documents/QuelaBot/venv/lib/python3.11/site-packages/aiopoke/objects/resources/pokemon/pokemon.py", line 89, in <listcomp>
    self.past_abilities = [PastAbility(**past_type) for past_type in past_types]
                           ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: PastAbility.__init__() got an unexpected keyword argument 'types'
```

**Desktop (please complete the following information):**
 - OS: macOS Vetura 13.5.2
 - Browser: Safari
 - Version: AioPoke v0.1.7
 - Python: 3.11.5

**Additional context**
It could just be me, but I'd appreciate any insights into fixing this error I'm getting. 

Thanks so much!

**Comment by beastmatser** [comment]
It was a simple typo, should be fixed by 6578e4456cedcacff3c28331229be49dd52e56f4. I'll release this as soon as #81 can be merged, so be sure to pull the most recent version from github. Thank you for reporting this!
